### ISSUE TITLE
startup rendering erros

### ISSUE THREAD

**Issue by alexeyknyshev** [novembermonk/kiui#16] opened 2015-05-01 14:16 UTC
There is no rounded windows' edges before style switching. Moreover, other things are broken. Such scrollbar in "Filtered List" demo.

You can see some from videos in:
- black background in #15 
- no scrollbar in "Filtered List" demo #14 

Regards, Alexey Knyshev

**Comment by hugoam** [comment] 2015-05-01 14:39
These should have been fixed with the yesterday commits.
Please update and report back if they persist.

**Closed as completed** 2015-05-01 14:42 UTC

**Comment by alexeyknyshev** [comment] 2015-05-01 14:59
- [x] Scrollbar in "Filterd List" fixed - confirmed
- [x] Black background issue is resolved (style change eliminates it) -> [_See below_]

**Comment by hugoam** [comment] 2015-05-01 15:05
I'm working on that one. (Will update on #15 when fixed)

**Comment by hugoam** [comment] 2015-05-01 15:26
Should be fixed in d42ff46, please confirm

**Comment by alexeyknyshev** [comment] 2015-05-01 15:41
Black background exists, maybe something due to my local merge. I'm going to check.

**Comment by hugoam** [comment] 2015-05-01 15:46
I'm not sure what you mean by the black background. You mean the visible flickering of the dropdown header ? (which I think is solved ?) Or something else ?
On my build I cannot see the problem

**Comment by alexeyknyshev** [comment] 2015-05-01 15:58
So, I'm going to create screenshoots

**Comment by alexeyknyshev** [comment] 2015-05-01 16:03
Just after starting kiui_example:

![no_style_black_background](https://cloud.githubusercontent.com/assets/823143/7432858/a28322f2-f034-11e4-8ffa-36d15b191472.png)

Selecting Blendish from styles combobox:

![no_style_black_background_2](https://cloud.githubusercontent.com/assets/823143/7432866/b519c45c-f034-11e4-8719-03bffb3512df.png)

**Comment by hugoam** [comment] 2015-05-01 16:05
Now I get it. That's not a bug.
The style that is selected on Startup is actually Blendish Dark and that's how it should look, it doesn't set any background colour for the header.
The only confusing thing is that the Dropdown is set to show "Blendish" when the default is actually Blendish Dark. So I'll fix that.

**Comment by alexeyknyshev** [comment] 2015-05-01 16:16
Great, ty.
