### ISSUE TITLE
Rendering errors

### ISSUE THREAD

**Issue by alexeyknyshev** [novembermonk/kiui#10] opened 2015-04-25 09:22 UTC
Screenshots from emscripten demo
**1. No round corners:**
![progress_bar_rounded_edge_error](https://cloud.githubusercontent.com/assets/823143/7332389/b060bbb2-eb45-11e4-9f53-0fd9e5eb53bc.png)

**2. Wrong background rect:**
![menu_background_rendering_error](https://cloud.githubusercontent.com/assets/823143/7332406/a3308840-eb46-11e4-857b-961ccad5a517.png)

**3.Something wrong with "Photoshop" theme:**
![photoshop_theme_bug](https://cloud.githubusercontent.com/assets/823143/7332426/2a711612-eb47-11e4-8352-5709ccacddbd.png)

**4.Switching themes brings elements position error**
Reproduce, select Window demo and switch from "Blendish" to "Turbo" theme:
![switching_from_blendish_to_turbo](https://cloud.githubusercontent.com/assets/823143/7332433/b75f6826-eb47-11e4-8fa7-11d2cdaf3a94.png)
Recreating window (select Window demo, which creates new kiui v0.1 titled window mostly eliminates error):
![photoshop_theme_bug_2](https://cloud.githubusercontent.com/assets/823143/7332439/1db5dce0-eb48-11e4-9fdd-f8238ba5e26b.png)

**Comment by alexeyknyshev** [comment] 2015-04-25 09:51
Big lists makes scrollbar too small which producess "rect" with negative height
ok:
![scrollbar_resize_bug](https://cloud.githubusercontent.com/assets/823143/7332465/3ffabcf2-eb49-11e4-8c68-37d32ec2c43c.png)
resizing to smaller window --> smaller scrollbar, baad:
![scrollbar_resize_bug_2](https://cloud.githubusercontent.com/assets/823143/7332469/76ef390e-eb49-11e4-94d8-d54397e1c284.png)
Smaller, transforms into rect (due to negative height?)
![photoshop_theme_bug_3](https://cloud.githubusercontent.com/assets/823143/7332475/bd4a4164-eb49-11e4-8123-b9b2c5f5dca1.png)
:

**Comment by hugoam** [comment] 2015-04-26 21:36
N°1, 2 and 5 are fixed in 7ad73ca.
N°3 is not a bug, the photoshop style is just an empty stub for now.
N°4 fixed in e9e8938.

**Closed as completed by hugoam** 2015-04-26 21:36 UTC
