### ISSUE TITLE
Filtered demo crash

### ISSUE THREAD

**Issue by alexeyknyshev** [novembermonk/kiui#14] opened 2015-05-01 14:04 UTC
Crash reproduction video:
https://www.youtube.com/watch?v=OzHMTXk9bs8

open Filtered demo -> open Window demo -> put \* as filter in TypeIn -> close Window demo -> clear filer -> open Window demo -> put \* as filter in TypeIn -> SEGFAULT

Rearads, Alexey Knyshev

**Comment by hugoam** [comment] 2015-05-01 14:40
Reproduced. I'll try to find the cause.

**Comment by hugoam** [comment] 2015-05-01 19:56
Found it ! Should be fixed in e3b74fc

**Closed as completed** 2015-05-01 21:42 UTC
